change to fizsh-1.0.1 source tree.

diff --git a/fizsh-1.0.1/scripts/zsh-syntax-highlighting b/fizsh-1.0.1/scripts/zsh-syntax-highlighting
--- a/fizsh-1.0.1/scripts/zsh-syntax-highlighting
+++ b/fizsh-1.0.1/scripts/zsh-syntax-highlighting
@@ -82,7 +82,7 @@ _zsh_check-path() {
   [[ -z ${(Q)arg} ]] && return 1
   [[ -e ${(Q)arg} ]] && return 0
   [[ ! -e ${(Q)arg:h} ]] && return 1
-  [[ ${#BUFFER} == $end_pos && -n $(print ${(Q)arg}*(N)) ]] && return 0
+  [[ ${BUFFER} != "-" && ${BUFFER} != "\\-" && ${BUFFER} != "-\\" ]] && [[ ${#BUFFER} == $end_pos && -n $(print ${(Q)arg}*(N)) ]] && return 0
   return 1
 }
 
@@ -221,7 +221,7 @@ _zsh_highlight-zle-buffer() {
 # Bind all ZLE events from zle -la to highlighting function.
 _zsh_highlight-install() {
   zmodload zsh/zleparameter 2>/dev/null || {
-    echo 'zsh-syntax-highlighting:zmoadload error. exiting.' >&2; return -1
+    echo 'zsh-syntax-highlighting:zmodload error. exiting.' >&2; return -1
   }
   local -a events; : ${(A)events::=${@:#(_*|orig-*|.run-help|.which-command)}}
   local clean_event
@@ -250,4 +250,3 @@ _zsh_highlight-install() {
   done
 }
 _zsh_highlight-install "${(@f)"$(zle -la)"}"
-
