change to fizsh-0.0.1-2 source tree.

diff --git a/etc/fizsh/zsh-syntax-highlighting b/etc/fizsh/zsh-syntax-highlighting
--- a/etc/fizsh/zsh-syntax-highlighting
+++ b/etc/fizsh/zsh-syntax-highlighting
@@ -1,10 +1,33 @@
 #!/usr/bin/env zsh
+# -------------------------------------------------------------------------------------------------
+# Copyright (c) 2010-2011 zsh-syntax-highlighting contributors
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without modification, are permitted
+# provided that the following conditions are met:
+#
+#  * Redistributions of source code must retain the above copyright notice, this list of conditions
+#    and the following disclaimer.
+#  * Redistributions in binary form must reproduce the above copyright notice, this list of
+#    conditions and the following disclaimer in the documentation and/or other materials provided
+#    with the distribution.
+#  * Neither the name of the zsh-syntax-highlighting contributors nor the names of its contributors
+#    may be used to endorse or promote products derived from this software without specific prior
+#    written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
+# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
+# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
+# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
+# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
+# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# -------------------------------------------------------------------------------------------------
 # -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
 # vim: ft=zsh sw=2 ts=2 et
+# -------------------------------------------------------------------------------------------------
 
-# Copyleft 2011 zsh-syntax-highlighting contributors
-# http://github.com/nicoulaj/zsh-syntax-highlighting
-# All wrongs reserved.
 
 # Token types styles.
 typeset -gA ZSH_HIGHLIGHT_STYLES
@@ -43,27 +66,9 @@ ZSH_HIGHLIGHT_MATCHING_BRACKETS_STYLES=(
   'fg=cyan,bold'
 )
 
-# Tokens that are always followed by a command.
+# Tokens that are always immediately followed by a command.
 ZSH_HIGHLIGHT_TOKENS_FOLLOWED_BY_COMMANDS=(
-  '|'
-  '||'
-  ';'
-  '&'
-  '&&'
-  'sudo'
-  'start'
-  'time'
-  'strace'
-  'noglob'
-  'nocorrect'
-  'command'
-  'builtin'
-  'whence'
-  'which'
-  'where'
-  'whereis'
-  'xargs'
-  'zargs'
+  '|' '||' ';' '&' '&&' 'noglob' 'nocorrect' 'builtin'
 )
 
 # ZLE highlight types.
@@ -74,10 +79,10 @@ zle_highlight=(
 
 # Check if the argument is a path.
 _zsh_check-path() {
-  [[ -z $arg ]] && return 1
-  [[ -e $arg ]] && return 0
-  [[ ! -e ${arg:h} ]] && return 1
-  [[ ${#BUFFER} == $end_pos && -n $(print $arg*(N)) ]] && return 0
+  [[ -z ${(Q)arg} ]] && return 1
+  [[ -e ${(Q)arg} ]] && return 0
+  [[ ! -e ${(Q)arg:h} ]] && return 1
+  [[ ${#BUFFER} == $end_pos && -n $(print ${(Q)arg}*(N)) ]] && return 0
   return 1
 }
 
@@ -214,22 +219,35 @@ _zsh_highlight-zle-buffer() {
 # reason).  You can see the default setup using "zle -l -L".
 
 # Bind all ZLE events from zle -la to highlighting function.
-local clean_event
-for event in $(zle -la); do
-  case $event in
-    _*|orig-*|.run-help|.which-command)
-      ;;
-    accept-and-menu-complete)
-      eval "$event() { builtin zle .$event && _zsh_highlight-zle-buffer } ; zle -N $event"
-      ;;
-    [^\.]*complete*)
-      eval "zle -C orig-$event .$event _main_complete ; $event() { builtin zle orig-$event && _zsh_highlight-zle-buffer } ; zle -N $event"
-      ;;
-    .*)
-      clean_event=$event[2,${#event}] # Remove the leading dot in the event name
-      eval "$clean_event() { builtin zle $event && _zsh_highlight-zle-buffer } ; zle -N $clean_event"
-      ;;
-    *)
-      ;;
-  esac
-done
+_zsh_highlight-install() {
+  zmodload zsh/zleparameter 2>/dev/null || {
+    echo 'zsh-syntax-highlighting:zmoadload error. exiting.' >&2; return -1
+  }
+  local -a events; : ${(A)events::=${@:#(_*|orig-*|.run-help|.which-command)}}
+  local clean_event
+  for event in $events; do
+    if [[ "$widgets[$event]" == completion:* ]]; then
+      eval "zle -C orig-$event ${${${widgets[$event]}#*:}/:/ } ; $event() { builtin zle orig-$event && _zsh_highlight-zle-buffer } ; zle -N $event"
+    else
+      case $event in
+        accept-and-menu-complete)
+          eval "$event() { builtin zle .$event && _zsh_highlight-zle-buffer } ; zle -N $event"
+          ;;
+        .*)
+          clean_event=$event[2,${#event}] # Remove the leading dot in the event name
+          case ${widgets[$clean_event]-} in
+            (completion|user):*)
+              ;;
+            *)
+              eval "$clean_event() { builtin zle $event && _zsh_highlight-zle-buffer } ; zle -N $clean_event"
+              ;;
+          esac
+          ;;
+        *)
+          ;;
+      esac
+    fi
+  done
+}
+_zsh_highlight-install "${(@f)"$(zle -la)"}"
+
